# Generated by Django 4.1.3 on 2024-09-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
