# Generated by Django 4.1.3 on 2025-06-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_printer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='manufacture_date',
            field=models.CharField(max_length=100),
        ),
    ]
