# Generated by Django 4.1.3 on 2025-06-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_printer_manufacture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
