# Generated by Django 4.1.3 on 2025-09-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_printer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='manufacture_date',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='model',
        ),
    ]
