# Generated by Django 4.1.3 on 2025-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_printer_brand_remove_printer_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='brand',
            field=models.CharField(default='Brand', max_length=100),
        ),
        migrations.AddField(
            model_name='printer',
            name='comments',
            field=models.TextField(blank=True, default='Comments', null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AddField(
            model_name='printer',
            name='location',
            field=models.CharField(default='Location', max_length=255),
        ),
        migrations.AddField(
            model_name='printer',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17),
        ),
        migrations.AddField(
            model_name='printer',
            name='manufacture_date',
            field=models.CharField(default='1900-00-00', max_length=100),
        ),
        migrations.AddField(
            model_name='printer',
            name='model',
            field=models.CharField(default='Model', max_length=100),
        ),
    ]
